name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Setup Vars
        id: vars
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          echo "git_hash=${git_hash}" >> $GITHUB_ENV
          echo "git_branch=${git_branch}" >> $GITHUB_ENV
      - name: Build PlatformIO Project
        run: pio run
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
            name: StarMod-esp32-${{env.git_branch}}-${{env.git_hash}}.bin
            path: .pio/build/esp32dev/firmware.bin
            retention-days: 30

